### PR TITLE
Added linter

### PR DESCRIPTION
**Pull request by blowin**
* Added .editorconfig
* Create linter.yml
* Fixed all code style issues

### CODE REVIEW

**Comment by podkolzzzin** [comment]
It is very cool commit. 
Can you please separate linter setup and all fixes in 2 PRs?

There are some pending PRs now and it would be difficult to merge it.

**Review by podkolzzzin — CHANGES_REQUESTED** [review]
It is very cool commit.
Can you please separate linter setup and all fixes in 2 PRs?

There are some pending PRs now and it would be difficult to merge it.

**Comment by blowin** [comment]
Of course

**Comment by blowin** [comment]
Removed the formatting fixes in the files. 

Left the minimum configuration, so you can configure it to the needs of the project.

**Pull request merged**
