### PR TITLE
Feature/add script loading support 32

### PR DESCRIPTION
**Pull request by vitaliy-bezugly**
# This pull request makes the following changes:
- Fixes issue: #32 

I have implemented a script file upload feature using drag and drop or file selection in a dialog box. 

## File changes:
- frontend/package.json: the frontend app didn't run so after some time I realized that in the <code>package.json</code> file didn't contain some importand dependencies
- frontend/src/components/FileUploader/FileUploader.tsx: added component for uploading files
- frontend/src/components/FileUploader/file-uploader.css: added styles for FileUploader component
- frontend/src/containers/EditorCard/EditorCard.tsx: implemented new features into EditorCard
- src/QueryPressure.UI/Resources.yml: added new localization resources for file uploading 

## Design: 
- File dialog button:
image
- In UA localization: 
image
- After uploading file:
image
- After Drag & Drop:
image

### CODE REVIEW

**Comment by vitaliy-bezugly** [comment]
@podkolzzzin This PR is ready for review. I am open to any advice and suggestions.

**Comment by podkolzzzin** [comment]
I like this PR a lot!
The code is OK and the PR decoration is really cool!

Thank you very much!

**Comment by podkolzzzin** [comment]
Started to use it and understood that, probably, it has eaten to much space.

I'll probably, suggest to update this:
- Use icon for the 'Upload' button
- Move both buttons to the status bar

**Comment by vitaliy-bezugly** [comment]
> Started to use it and understood that, probably, it has eaten to much space.
> 
> I'll probably, suggest to update this:
> 
> * Use icon for the 'Upload' button
> * Move both buttons to the status bar

Thanks for the feedback. I will make these changes as soon as possible!

**Comment by podkolzzzin** [comment]
One more thing:
- The 'Select File' button is clickable but looks like disabled (if no file selected)
- The 'Upload' button does nothing(if no file selected) but looks enabled

**Comment by vitaliy-bezugly** [comment]
> One more thing:
> 
> * The 'Select File' button is clickable but looks like disabled (if no file selected)
> * The 'Upload' button does nothing(if no file selected) but looks enabled

I took into account all the comments and corrected them in the new PR: #49

**Pull request merged**
